### ISSUE TITLE
Support parskip configuration

### ISSUE THREAD

**Issue by rogerbosman** [elauksap/focus-beamertheme#25] opened 2022-04-26 13:38 UTC
By default this theme has no spacing between paragraphs, i.e.

```
line1

line2
```

in the `.tex` will get you 

```
line1
line2
```

in the `.pdf`. You could set something like
```
\setlength{\parskip}{\medskipamount}
```

which would emit some space between the lines. However, then this also applies to an itemize/enumerate that is _attached_ to the paragraph above, i.e.

```
line1
\begin{itemize}
\item foo
\end{itemize}
```

would get you the same as

```
line1

\begin{itemize}
\item foo
\end{itemize}
```
namely something like
```
line1

- foo
```
this can be fixed with
```
\newcommand{\noskip}{\vspace{-\parskip}}
...
line1
\noskip
\begin{itemize}
\item foo
\end{itemize}
```
but ideally this is done automatically. I don't have the best knowledge of beamer themes, so I'm unsure if this is even something that a thememaker would solve, or would be down to beamer configuration. Still, the theme _does_ contain beamer config, right? So it would be applicable to implement here?

**Comment by pcafrica** [comment] 2022-04-26 13:56
Dear @rogerbosman,

thanks for the hint! Unfortunately, this is not _Focus_-related but is the default Beamer behaviour.

See, _e.g._, the following minimal example, which reproduces the issue without using `Focus`:

```{.tex}
\documentclass{beamer}

\begin{document}
    \begin{frame}
        line1
        
        line2
    \end{frame}
\end{document}
```

Setting `\parskip` as you suggested looks like a good workaround.

As there is not much that I can do about it, I'm going to close this issue.
Feel free to re-open it in case you have further comments or questions.

Best,
elauksap

**Closed as completed by pcafrica** 2022-04-26 13:56 UTC
